DROP TABLE IF EXISTS dokumenty_typy CASCADE;
DROP TABLE IF EXISTS dokumenty CASCADE;
DROP TABLE IF EXISTS miejsca_typy CASCADE;
DROP TABLE IF EXISTS miejsca CASCADE;
DROP TABLE IF EXISTS miejsca_dokumenty CASCADE;
DROP TABLE IF EXISTS miejsca_krainy CASCADE;
DROP TABLE IF EXISTS wydarzenia_typy CASCADE;
DROP TABLE IF EXISTS wydarzenia CASCADE;
DROP INDEX IF EXISTS wydarzenia_data_index CASCADE;
DROP INDEX IF EXISTS wydarzenia_typ_index CASCADE;
DROP TABLE IF EXISTS wydarzenia_dokumenty CASCADE;
DROP TABLE IF EXISTS kolory CASCADE;
DROP TABLE IF EXISTS religie CASCADE;
DROP TABLE IF EXISTS religie_dokumenty CASCADE;
DROP TABLE IF EXISTS funkcje CASCADE;
DROP TABLE IF EXISTS osoby CASCADE;
DROP TABLE IF EXISTS rody CASCADE;
DROP TABLE IF EXISTS rody_dokumenty CASCADE;
DROP TABLE IF EXISTS rody_wydarzenia CASCADE;
DROP TABLE IF EXISTS rody_miejsca CASCADE;
DROP TABLE IF EXISTS rody_zaleznosci CASCADE;
DROP TABLE IF EXISTS osoby_rody CASCADE;
DROP TABLE IF EXISTS osoby_funkcje CASCADE;
DROP TABLE IF EXISTS osoby_dokumenty CASCADE;
DROP TABLE IF EXISTS osoby_wydarzenia CASCADE;
DROP FUNCTION IF EXISTS set_dokument_wiarygodny () CASCADE;
DROP TRIGGER IF EXISTS set_dokument_wiarygodny ON dokumenty CASCADE;
DROP FUNCTION IF EXISTS get_wydarzenia (int, wydarzenie_typy) CASCADE;
DROP FUNCTION IF EXISTS get_data_smierci (int) CASCADE;
DROP FUNCTION IF EXISTS czy_byla_zywa (int, date) CASCADE;
DROP FUNCTION IF EXISTS czy_moze_byc_rodzicem (int, int) CASCADE;
DROP FUNCTION IF EXISTS check_rodzice () CASCADE;
DROP TRIGGER IF EXISTS check_rodzice ON osoby CASCADE;
DROP FUNCTION IF EXISTS get_przodkowie (int, int) CASCADE;
DROP FUNCTION IF EXISTS get_potomkowie (int, int) CASCADE;
DROP FUNCTION IF EXISTS czy_spokrewnieni (int, int) CASCADE;
DROP FUNCTION IF EXISTS kto_bral_udzial (int) CASCADE;
DROP FUNCTION IF EXISTS get_zyjacy (date, date) CASCADE;
DROP FUNCTION IF EXISTS check_wydarzenie_osoba () CASCADE;
DROP TRIGGER IF EXISTS check_wydarzenie_osoba ON osoby_wydarzenia CASCADE;
DROP FUNCTION IF EXISTS update_osoby_funkcje_jesli_smierc () CASCADE;
DROP TRIGGER IF EXISTS update_osoby_funkcje_jesli_smierc ON osoby_wydarzenia CASCADE;
DROP FUNCTION IF EXISTS ile_osob_zylo (int) CASCADE;
DROP VIEW IF EXISTS protoplasci CASCADE;
DROP FUNCTION IF EXISTS check_miejsca_krainy () CASCADE;
DROP TRIGGER IF EXISTS check_miejsca_krainy ON miejsca_krainy CASCADE;
DROP FUNCTION IF EXISTS check_rody_stolice () CASCADE;
DROP TRIGGER IF EXISTS check_rody_stolice ON rody CASCADE;
DROP FUNCTION IF EXISTS get_malzenstwa (int) CASCADE;
DROP FUNCTION IF EXISTS get_bekarci (int) CASCADE;
