--zamki
INSERT INTO miejsca(nazwa,typ) VALUES
	('Smocza Skała',1),
	('Harrenhal',1),
	('Koniec Burzy',1),
	('Winterfell',1),
	('Casterly Rock',1),
	('Czarny Zamek',1),
	('Dreadfort',1),
	('Czerwona Twierdza',1),
	('Karhold',1),
	('Orle Gniazdo',1),
	('Fosa Cailin',1),
	('Bliźniaki',1),
	('Summerhal',1),
	('Torrhens Square',1),
	('Ashemark',1),
	('Blackmont',1),
	('Dębowa Tarcza',1),
	('Ghaston Grey',1),
	('Hornvale',1),
	('Kamienne drzwi',1),
	('Pinkmaiden',1),
	('Riverrun',1),
	('Sarsfield',1),
	('Seagard',1),
	('Sobolowy Dwór',1),
	('Starfall',1),
	('Staw Dziewic',1),
	('Wschodnia Strażnica',1),
	('Wysogród',1),
	('Złoty Ząb',1)
;

--miasta
INSERT INTO miejsca(nazwa,typ) VALUES
	('Braavos',2),
	('Meereen',2),
	('Asshai',2),
	('Wolne Miasta',2),
	('Stara Valyria',2),
	('Astapor',2),
	('Pentos',2),
	('Vaes Dothrak',2),
	('Lys',2),
	('Lorath',2),
	('Stare Miasto',2),
	('Słoneczna Włócznia',2),
	('Myr',2),
	('Norvos',2),
	('Tyrosh',2),
	('Qohor',2),
	('Lannisport',2),
	('Stare Ghis',2),
	('Biała Przystań',2),
	('Nowe Ghis',2),
	('Bayasabhad',2),
	('Tolos',2),
	('Mantarys',2),
	('Elyria',2),
	('Samyrian',2),
	('Gulltown',2),
	('Tyria',2),
	('Oros',2),
	('Chroyane',2),
	('Bhorash',2),
	('Ny Sar',2),
	('Ar Noy',2),
	('Saer Mell',2),
	('Królewska Przystań',2)
;

--krainy
INSERT INTO miejsca(nazwa,typ) VALUES
	('Dolina Arrynów',3),
	('Dorne',3),
	('Dorzecze',3),
	('Krainy Burzy',3),
	('Królestwo Zachodu',3),
	('Reach',3),
	('Włości Korony',3),
	('Za murem',3),
	('Żelazne wyspy',3),
	('Północ',3),
	('Essos',3)
;

--ziemie
INSERT INTO ziemie VALUES
	(1,'duży',NULL),
	(2,'duży',NULL),
	(3,'średni',NULL),
	(4,'mały',NULL),
	(5,'duży',NULL),
	(6,'średni',NULL),
	(7,'średni',NULL),
	(8,'duży',NULL),
	(9,'duży',NULL),
	(10,'duży',NULL)
;
