--Herby rodów
INSERT INTO dokumenty(typ,ścieżka,wiarygodny) VALUES
	(11,'Graphics/Arryn.png',true),
	(11,'Graphics/Baratheon.png',true),
	(11,'Graphics/Bolton.png',true),
	(11,'Graphics/Cassel.png',true),
	(11,'Graphics/Bolling.png',true),
	(11,'Graphics/Brax.png',true),
	(11,'Graphics/Buckler.png',true),
	(11,'Graphics/Cerwyn.png',true),
	(11,'Graphics/Clegane.png',true),
	(11,'Graphics/Crakehall.png',true),
	(11,'Graphics/Dondarrion.png',true),
	(11,'Graphics/Farring.png',true),
	(11,'Graphics/Florent.png',true),
	(11,'Graphics/Haigh.png',true),
	(11,'Graphics/Hightower.png',true),
	(11,'Graphics/Karstark.png',true),
	(11,'Graphics/Mallister.png',true),
	(11,'Graphics/Martell.png',true),
	(11,'Graphics/Payne.png',true),
	(11,'Graphics/Reed.png',true),
	(11,'Graphics/Reyne.png',true),
	(11,'Graphics/Sarwyck.png',true),
	(11,'Graphics/Selmy.png',true),
	(11,'Graphics/Tallhart.png',true),
	(11,'Graphics/Tyrell.png',true),
	(11,'Graphics/Umber.png',true),
	(11,'Graphics/Westerling.png',true),
	(11,'Graphics/Yronwood.png',true),
	(11,'Graphics/Greyjoy.png',true),
	(11,'Graphics/Frey.png',true),
	(11,'Graphics/Lannister.png',true),
	(11,'Graphics/Mollen.png',true),
	(11,'Graphics/Stark.png',true),
	(11,'Graphics/Targaryen.png',true)
;	

	